name: datastructurex
description: Bloc state management list update examples.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1            # BloC (https://pub.dev/packages/flutter_bloc)
  equatable: ^2.0.3               # Equality Comparision (https://pub.dev/packages/equatable)



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
